# Generated by Django 4.2.4 on 2024-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_bookingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
